<a href="https://colab.research.google.com/github/fathimashik/TDS_PROJECT/blob/main/Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_csv('/content/GA_2_dataset.csv')
df.dtypes

PlayerID                       int64
Age                          float64
Gender                        object
Location                      object
GameGenre                     object
PlayTimeHours                float64
InGamePurchases              float64
GameDifficulty                object
SessionsPerWeek                int64
AvgSessionDurationMinutes      int64
PlayerLevel                    int64
AchievementsUnlocked           int64
EngagementLevel               object
dtype: object

In [5]:
count = df[
    (df["Gender"] == "Male") &
    (df["Location"] == "Europe") &
    (df["InGamePurchases"] == "Yes")
].shape[0]

print(count)

0

In [6]:
count = df[
    (df["Gender"] == "Male") &
    (df["Location"] == "Europe") &
    (df["InGamePurchases"] > 0)
].shape[0]

print(count)

299

In [7]:
count = df[
    (df["Age"] < 18) &
    (df["PlayTimeHours"] > 10)
].shape[0]

print(count)

453

In [8]:

y = df["EngagementLevel"]


X = df.drop("EngagementLevel", axis=1)
total_null = df.isnull().sum().sum()

print(total_null)

3337

In [12]:
from sklearn.model_selection import train_test_split

# Split data (20% test, 80% train)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)
y_train.value_counts()

EngagementLevel
Medium    3983
Low       2021
High      1996
Name: count, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

# Split data (20% test, 80% train)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)
y_train.value_counts()
y_train.value_counts().idxmin()

'High'

In [13]:
import numpy as np

X_train = X_train.replace("Unknown", np.nan)
X_test = X_test.replace("Unknown", np.nan)
age_mean = X_train["Age"].mean()
difficulty_mode = X_train["GameDifficulty"].mode()[0]
X_train["Age"].fillna(age_mean, inplace=True)
X_test["Age"].fillna(age_mean, inplace=True)
X_train["Location"].fillna("Other", inplace=True)
X_test["Location"].fillna("Other", inplace=True)
X_train["GameDifficulty"].fillna(difficulty_mode, inplace=True)
X_test["GameDifficulty"].fillna(difficulty_mode, inplace=True)
X_train["InGamePurchases"].fillna('0', inplace=True)
X_test["InGamePurchases"].fillna('0', inplace=True)
age_sum_test = round(X_test["Age"].sum(), 2)

print(age_sum_test)

63585.24

/tmp/ipython-input-3324588622.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train["Age"].fillna(age_mean, inplace=True)
/tmp/ipython-input-3324588622.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test["Age"].fillna(age_mean, inplace=True)
/tmp/ipython-input-3324588622.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train["Location"].fillna("Other", inplace=True)
/tmp/ipython-input-3324588622.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test["Location"].fillna("Other", inplace=True)
/tmp/ipython-input-3324588622.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train["GameDifficulty"].fillna(difficulty_mode, inplace=True)
/tmp/ipython-input-3324588622.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test["GameDifficulty"].fillna(difficulty_mode, inplace=True)
/tmp/ipython-input-3324588622.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train["InGamePurchases"].fillna('0', inplace=True)
/tmp/ipython-input-3324588622.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  X_train["InGamePurchases"].fillna('0', inplace=True)
/tmp/ipython-input-3324588622.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test["InGamePurchases"].fillna('0', inplace=True)
/tmp/ipython-input-3324588622.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  X_test["InGamePurchases"].fillna('0', inplace=True)

In [14]:
X_train = X_train.drop("PlayerID", axis=1)
X_test = X_test.drop("PlayerID", axis=1)
difficulty_mapping = {"Easy": 0, "Medium": 1, "Hard": 2}

X_train["GameDifficulty"] = X_train["GameDifficulty"].map(difficulty_mapping)
X_test["GameDifficulty"] = X_test["GameDifficulty"].map(difficulty_mapping)
X_train = pd.get_dummies(
    X_train,
    columns=["Gender", "Location", "GameGenre"],
    drop_first=True
)

X_test = pd.get_dummies(
    X_test,
    columns=["Gender", "Location", "GameGenre"],
    drop_first=True
)
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

import numpy as np

total_sum = round(np.sum(X_test_scaled[:5]), 2)

print(total_sum)

-7.17

In [ ]:
from google.colab import drive
drive.mount('/content/drive')